### ISSUE TITLE
make issue 

### ISSUE THREAD

**Issue by vivekpk007** [TinkerBoard/android-6.0.1_kernel#2]
`Makefile:805: *** multiple target patterns.  Stop.`
this is the issue showing when i am trying to make

**Comment by jamess-huang** [comment]
You may reference the below link for building kernel.
https://tinkerboarding.co.uk/wiki/index.php/Software#Android_6.0.1_kernel

**Comment by jamess-huang** [comment]
close it. If any question further, please reopen it
