### ISSUE TITLE
Touch support is not working on RPI Display

### ISSUE THREAD

**Issue by sobrinho** [TinkerBoard/android-6.0.1_kernel#3]
Derived from https://github.com/TinkerBoard/debian_kernel/issues/24.

You can see in this video that it is working as expected when in landscape mode but when I open the Google Calendar and it forces the OS to be in portrait mode, it keeps the touch working in landscape.

You can see that if I "guess" what the position would be in landscape mode, it works, but you can imagine how is that hard when you have to press a specific button in the screen.

This is happening to all applications that forces to be in portrait modes like Google Calendar, Spotify and Waze.

It is not the end of the world since those screens are more common during the login or a help but it is difficult to operate the screen like that.

https://youtu.be/oBKFvZK7v0Y

![Screenshot of the version](https://user-images.githubusercontent.com/26460/46160564-707e3f80-c259-11e8-862d-e22155f8d84d.JPG)

**Comment by jamess-huang** [comment]
Hi, sobrinho
   This issue has been solved on Android N.
   https://github.com/TinkerBoard/android-7.1.2_kernel/issues/1
   May we close this issue ? 

   And we will solve other panel issues on Android N.

**Comment by sobrinho** [comment]
Sure, thanks!
